### ISSUE TITLE
Background doesn't change when changing theme

### ISSUE THREAD

**Issue by ckt114** [archcraft-os/archcraft-xfce#6]
When changing the theme the background doesn't change. It works when I run the live ISO session but doesn't work after installed onto disk. What logs can I look or script to fix for it to work? TIA.

**Comment by ckt114** [comment]
I did some debugging and it the background only changes when it's a single monitor. When I have multiple displays it the background won't change.

**Comment by adi1090x** [comment]
Edit `~/.config/xfce-themes/apply.sh` script and modify the wallpaper funct, I don't have monitor(s) to implement that.
